version: '3'
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health_center
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"