name: Integración continua

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v2

      - name: Configurar el JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Ejecutar las pruebas
        run: ./gradlew test --no-daemon

        on:
          push:
